version: '3'
name: zeppelin-prod
services:
  nginx:
    build:
      context: .
      dockerfile: docker/production/nginx-insecure/Dockerfile
      args:
        API_PORT: ${API_PORT:?Missing API_PORT}
        DOCKER_PROD_DOMAIN: ${DOCKER_PROD_DOMAIN:?Missing DOCKER_PROD_DOMAIN}
    volumes:
      - ./:/zeppelin
    networks:
      - default
      - traefik-public
    labels:
      traefik.enable: true

      traefik.http.routers.zeppelin.rule: Host(`${DOCKER_PROD_DOMAIN}`)
      traefik.http.routers.zeppelin.entrypoints: ${DOCKER_PROD_TRAEFIK_ENTRYPOINTS}
      traefik.http.routers.zeppelin.tls: ${DOCKER_PROD_TRAEFIK_TLS}
      traefik.http.routers.zeppelin.tls.certresolver: ${DOCKER_PROD_TRAEFIK_TLS_CERTRESOLVER}
      traefik.http.routers.zeppelin.service: zeppelin

      traefik.http.services.zeppelin.loadbalancer.server.port: 80

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_PROD_MYSQL_ROOT_PASSWORD?:Missing DOCKER_PROD_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: zeppelin
      MYSQL_USER: zeppelin
      MYSQL_PASSWORD: ${DOCKER_PROD_MYSQL_PASSWORD?:Missing DOCKER_PROD_MYSQL_PASSWORD}
    ports:
      - ${DOCKER_PROD_MYSQL_PORT:?Missing DOCKER_PROD_MYSQL_PORT}:3306
    volumes:
      - ./docker/production/data/mysql:/var/lib/mysql
    command: --authentication-policy=mysql_native_password
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=\"${DOCKER_PROD_MYSQL_ROOT_PASSWORD}\" --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 300s
      retries: 60

  migrate:
    depends_on:
      mysql:
        condition: service_healthy
    build:
      context: .
      dockerfile: docker/production/backend/Dockerfile
    command: ["npm", "run", "migrate-prod"]

  api:
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: docker/production/backend/Dockerfile
    restart: on-failure
    environment:
      DEBUG: ${DEBUG-}
    command: ["npm", "run", "start-api-prod"]
    networks:
      - default
      - traefik-public
    labels:
      traefik.enable: true

      traefik.http.middlewares.zeppelin-strip-api-prefix.stripprefix.prefixes: '/api'

      traefik.http.routers.zeppelin-api.rule: Host(`${DOCKER_PROD_DOMAIN}`) && PathPrefix(`/api`)
      traefik.http.routers.zeppelin-api.entrypoints: ${DOCKER_PROD_TRAEFIK_ENTRYPOINTS}
      traefik.http.routers.zeppelin-api.tls: ${DOCKER_PROD_TRAEFIK_TLS}
      traefik.http.routers.zeppelin-api.tls.certresolver: ${DOCKER_PROD_TRAEFIK_TLS_CERTRESOLVER}
      traefik.http.routers.zeppelin-api.service: zeppelin-api
      traefik.http.routers.zeppelin-api.middlewares: zeppelin-strip-api-prefix@docker

      traefik.http.services.zeppelin-api.loadbalancer.server.port: ${API_PORT:?Missing API_PORT}

  bot:
    depends_on:
      migrate:
        condition: service_completed_successfully
    build:
      context: .
      dockerfile: docker/production/backend/Dockerfile
    restart: on-failure
    environment:
      DEBUG: ${DEBUG-}
    command: ["/bin/bash", "/zeppelin/docker/production/start-bot.sh"]

networks:
  traefik-public:
    external: true
